# Programming Assignment 6
---
**Author:** Kerry Effinger  
**Version:** 1.0  
**Semester:** Fall 2020  

This *notebook* contains my solution to **Programming Assignment 6**

In [1]:
import numpy as np

# a

In [3]:
d = np.array([[10,20],[30,40]])

In [7]:
d

array([[10, 20],
       [30, 40]])

In [5]:
d1 = d **2

In [6]:
d1

array([[ 100,  400],
       [ 900, 1600]])

In [8]:
d2 = d + 100

In [9]:
d2

array([[110, 120],
       [130, 140]])

In [10]:
d3 = d * 5

In [11]:
d3

array([[ 50, 100],
       [150, 200]])

In [12]:
d4 = np.sqrt(d)

In [13]:
d4

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

# b

In [20]:
b = np.array(np.arange(3,30,3))

In [29]:
b.resize(3,3)

In [30]:
b

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [23]:
b2 = np.array(np.linspace(10,20,num=9))

In [31]:
b2.resize(3,3)

In [32]:
b2

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [33]:
b3 = b * b2

In [34]:
b3

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

# c

In [52]:
c1 = np.load('process1.npy')

In [53]:
c2 = np.load('process2.npy')

In [54]:
c3 = np.load('process3.npy')

In [55]:
c4 = np.load('process4.npy')

In [56]:
c5 = np.load('process5.npy')

In [60]:
stackedc = np.vstack((c1,c2,c3,c4,c5))

In [61]:
stackedc

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]], dtype=int32)

In [62]:
stackedc.mean(axis = 0)

array([72. , 27.8, 45.6, 12. , 47.8])